Dev
Nafarfy/toDoList pull request #1
Opened 2020-12-27 14:35 UTC by Nafarfy

2020-12-27 14:46 UTC, zem-aleks requested changes

2020-12-27 14:46 UTC, zem-aleks commented on css/main.css
> +    border: none !important;
avoid using of !important attribute. Probably it would be easier to make another class then use bootstrap border or check how it can be changed in the bootstrap

2020-12-27 14:46 UTC, zem-aleks commented on index.html
> +  <meta name="viewport" content="width=device-width, initial-scale=1.0">
What does this tag do? :)

2020-12-27 14:46 UTC, zem-aleks commented on index.html
> +  <div class="container col-sm-8 mt-5">
as far as I remember it's not recommended to mix container and column properties. one div should be container another div should have column classes

2020-12-27 14:46 UTC, zem-aleks commented on index.html
> +        <div class="card-task-add col-sm-4">
usually it's better do not mix columns and another components. For example, you have a block which is responsible for adding a new task and you add column responsibility to it. It means that if you use it somewhere else without column logic, it can be broken. Try to be careful with a logic mixing. 

Also it's good to check principle SOLID. At least let's start from S -> single responsibility.

2020-12-27 14:46 UTC, zem-aleks commented on index.html
> +              <a href="#"><i class="fas fa-times"></i></a>
check href="javascript: void(0)" or <button>

2020-12-28 15:35 UTC, Nafarfy commented on css/main.css
> +    border: none !important;
Created another class with bootstrap border style

2020-12-28 15:38 UTC, Nafarfy commented on index.html
> +  <div class="container col-sm-8 mt-5">
Divided container and column properties, by adding a block with column properties

2020-12-28 15:41 UTC, Nafarfy commented on index.html
> +        <div class="card-task-add col-sm-4">
Another block with column properties was added

2020-12-28 15:54 UTC, Nafarfy commented on index.html
> +  <meta name="viewport" content="width=device-width, initial-scale=1.0">
The viewport meta tag is needed to ensure the correct display of web page on different devices.
 content="width=device-width - it shows that width of the viewport  will be equal to the CSS width of the device

2020-12-28 17:29 UTC, zem-aleks requested changes

2020-12-28 17:29 UTC, zem-aleks commented on js/main.js
> +const ul = document.querySelector('.task-collection');
ul is a bad name. taskList, taskItemsList or something else more meaningful

2020-12-28 17:29 UTC, zem-aleks commented on js/main.js
> +  let inputValue = newTaskInput.value;
why let?

2020-12-28 17:29 UTC, zem-aleks commented on js/main.js
> +  const li = document.createElement('li');
If you've checked S from Solid, you may notice that this function already has a few responsibilities and I'd suggest to separate it to have another function which is responsible for creation of new element by a provided name/title

2020-12-28 17:29 UTC, zem-aleks commented on js/main.js
> +  const li = document.createElement('li');
to be honest, I don't like to have HTML DOM managing inside JS. You can make some errors during it's creation etc. It would be better if you have some hidden element or part of template in JS which can be cloned instead of a few operations to manage this item. 

And in general, the idea of adding element can be more elegant if you have JS array/object that contains data and some function renders this array. So in this functiona you will add one element to thearray and some other part of code will update the list

2020-12-28 17:29 UTC, zem-aleks commented on js/main.js
> +ul.addEventListener('click', deleteTask);
jQuery approach. It has drawbacks. I'd love to see event listener on button and when an item is removed, we should remove such listener

2020-12-28 17:29 UTC, zem-aleks commented on js/main.js
> +const newTaskInput = document.querySelector('.add-task');
Overall your logic is mixed with the view. It would be nice to have low coupling.

Let's imagine that you have a list. How it can look in JS? It could be array of records:

`const list = [
  { id: 1, title: 'Item 1'},
  { id: 2, title: 'Item 2'}
]`

When you add a record, you push new item to the list. When you delete, you remove this item. It's your app logic. Also you have view that you would like to connect with this logic. To do it, you should call those functions in event listeners properly. 

And of course we need a function that will render your list. During rendering you can iterate through all items and call renderItem function.  Be careful with dom operations, they are expensive.

2020-12-29 14:50 UTC, merged